export const GET_ALL_HOTELS = 'GET_ALL_HOTELS'
export const LOCATION_FILTER = 'LOCATION_FILTER'
export const GET_HOTEL = 'GET_HOTEL'
export const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM'
export const LOGIN_USER = 'LOGIN_USER'
export const ROOM_SEARCH = 'ROOM_SEARCH'
export const GET_LOYALTY = 'GET_LOYALTY'
export const BOOK_ROOM = 'BOOK_ROOM'

export const BREAKFAST = 'BREAKFAST'
export const FITNESSROOM = 'FITNESSROOM'
export const POOL = 'POOL'
export const PARKING = 'PARKING'
export const MEALS = 'MEALS'